# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Haydar Acer
tagline:             'Haydar Acer'
description:         'Blog'
url:                 http://devvrim.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Haydar
  url:               https://twitter.com/devvrim
  email:             devvrim@gmail.com

# Custom vars
version:             2.0.0
twitter_username:   devvrim
github_username:   devvrim
facebook_username:   hokapuka
linkedin_username:   haydaracer
email: devvrim@gmail.com
